export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  TENANT_ADMIN = 'TENANT_ADMIN',
  OPERATIONS_MANAGER = 'OPERATIONS_MANAGER',
  WAREHOUSE_SUPERVISOR = 'WAREHOUSE_SUPERVISOR',
  FLEET_DISPATCHER = 'FLEET_DISPATCHER',
  DRIVER = 'DRIVER',
  FINANCE_OFFICER = 'FINANCE_OFFICER',
  AUDITOR = 'AUDITOR',
  CUSTOMER = 'CUSTOMER'
}

export enum TenantTier {
  STARTER = 'STARTER',
  PROFESSIONAL = 'PROFESSIONAL',
  ENTERPRISE = 'ENTERPRISE',
  UNLIMITED = 'UNLIMITED'
}

export enum OrderStatus {
  PENDING_VALIDATION = 'PENDING_VALIDATION',
  VALIDATED = 'VALIDATED',
  INVENTORY_RESERVING = 'INVENTORY_RESERVING',
  INVENTORY_RESERVED = 'INVENTORY_RESERVED',
  INVENTORY_FAILED = 'INVENTORY_FAILED',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAYMENT_CAPTURED = 'PAYMENT_CAPTURED',
  PAYMENT_FAILED = 'PAYMENT_FAILED',
  AWAITING_FULFILLMENT = 'AWAITING_FULFILLMENT',
  DISPATCH_SCHEDULED = 'DISPATCH_SCHEDULED',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  FAILED = 'FAILED'
}

export enum OrderPriority {
  LOW = 'LOW',
  STANDARD = 'STANDARD',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
  EMERGENCY = 'EMERGENCY'
}

export enum StockMovementType {
  INBOUND_RECEIPT = 'INBOUND_RECEIPT',
  OUTBOUND_DISPATCH = 'OUTBOUND_DISPATCH',
  ORDER_RESERVATION = 'ORDER_RESERVATION',
  RESERVATION_RELEASE = 'RESERVATION_RELEASE',
  BIN_TRANSFER = 'BIN_TRANSFER',
  DAMAGE_SCRAP = 'DAMAGE_SCRAP',
  CYCLE_COUNT_ADJUSTMENT = 'CYCLE_COUNT_ADJUSTMENT',
  RETURN_RESTOCK = 'RETURN_RESTOCK'
}

export enum WarehouseZoneType {
  RECEIVING_DOCK = 'RECEIVING_DOCK',
  BULK_STORAGE = 'BULK_STORAGE',
  PICK_FACE = 'PICK_FACE',
  COLD_STORAGE = 'COLD_STORAGE',
  HAZMAT_VAULT = 'HAZMAT_VAULT',
  PACKING_STATION = 'PACKING_STATION',
  DISPATCH_STAGING = 'DISPATCH_STAGING',
  RETURNS_QUARANTINE = 'RETURNS_QUARANTINE'
}

export enum ShipmentStatus {
  DRAFT = 'DRAFT',
  MANIFESTED = 'MANIFESTED',
  CARRIER_ASSIGNED = 'CARRIER_ASSIGNED',
  LOADING = 'LOADING',
  DISPATCHED = 'DISPATCHED',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  FAILED_ATTEMPT = 'FAILED_ATTEMPT',
  DELIVERED = 'DELIVERED',
  RETURNED_TO_HUB = 'RETURNED_TO_HUB',
  CANCELLED = 'CANCELLED'
}

export enum VehicleType {
  SPRINTER_VAN = 'SPRINTER_VAN',
  BOX_TRUCK_16FT = 'BOX_TRUCK_16FT',
  BOX_TRUCK_26FT = 'BOX_TRUCK_26FT',
  FLATBED_TRAILER = 'FLATBED_TRAILER',
  REFRIGERATED_REEFER = 'REFRIGERATED_REEFER',
  SEMI_TRAILER_53FT = 'SEMI_TRAILER_53FT',
  ELECTRIC_CARGO_VAN = 'ELECTRIC_CARGO_VAN'
}

export enum VehicleStatus {
  AVAILABLE = 'AVAILABLE',
  EN_ROUTE = 'EN_ROUTE',
  LOADING = 'LOADING',
  UNLOADING = 'UNLOADING',
  MAINTENANCE = 'MAINTENANCE',
  OUT_OF_SERVICE = 'OUT_OF_SERVICE'
}

export enum AccountType {
  ASSET_CASH = 'ASSET_CASH',
  ASSET_RECEIVABLES = 'ASSET_RECEIVABLES',
  ASSET_INVENTORY = 'ASSET_INVENTORY',
  LIABILITY_PAYABLES = 'LIABILITY_PAYABLES',
  LIABILITY_DEFERRED_REVENUE = 'LIABILITY_DEFERRED_REVENUE',
  EQUITY_CAPITAL = 'EQUITY_CAPITAL',
  EQUITY_RETAINED_EARNINGS = 'EQUITY_RETAINED_EARNINGS',
  REVENUE_FULFILLMENT = 'REVENUE_FULFILLMENT',
  REVENUE_SHIPPING = 'REVENUE_SHIPPING',
  EXPENSE_COGS = 'EXPENSE_COGS',
  EXPENSE_FLEET_FUEL = 'EXPENSE_FLEET_FUEL',
  EXPENSE_PAYMENT_GATEWAY_FEES = 'EXPENSE_PAYMENT_GATEWAY_FEES',
  EXPENSE_WAREHOUSE_OVERHEAD = 'EXPENSE_WAREHOUSE_OVERHEAD'
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  ISSUED = 'ISSUED',
  PAID = 'PAID',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  VOID = 'VOID',
  OVERDUE = 'OVERDUE',
  IN_DISPUTE = 'IN_DISPUTE'
}

export enum PaymentMethodType {
  CREDIT_CARD = 'CREDIT_CARD',
  ACH_BANK_TRANSFER = 'ACH_BANK_TRANSFER',
  SEPA_TRANSFER = 'SEPA_TRANSFER',
  ESCROW_SETTLEMENT = 'ESCROW_SETTLEMENT',
  COMMERCIAL_INVOICE_NET30 = 'COMMERCIAL_INVOICE_NET30'
}

export enum PaymentStatus {
  INITIATED = 'INITIATED',
  AUTHORIZED = 'AUTHORIZED',
  CAPTURED = 'CAPTURED',
  SETTLED = 'SETTLED',
  DECLINED = 'DECLINED',
  REFUNDED = 'REFUNDED',
  CHARGEBACK = 'CHARGEBACK'
}

export enum NotificationChannel {
  IN_APP = 'IN_APP',
  WEBSOCKET = 'WEBSOCKET',
  EMAIL = 'EMAIL',
  SMS = 'SMS',
  WEBHOOK = 'WEBHOOK',
  SLACK_BRIDGE = 'SLACK_BRIDGE'
}

export enum NotificationPriority {
  LOW = 'LOW',
  NORMAL = 'NORMAL',
  HIGH = 'HIGH',
  URGENT = 'URGENT'
}

export enum SagaStatus {
  STARTED = 'STARTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  COMPENSATING = 'COMPENSATING',
  COMPENSATED = 'COMPENSATED',
  FAILED = 'FAILED'
}
